### PR TITLE
CF-952 Bypass Lane

### PR DESCRIPTION
**Pull request by john-chrosniak**
# PR Details
## Description

This PR adds the bypass lane needed for the upcoming DOT HQ demo to both the center line route graph and the route graph designed for trailer usage.

## Related GitHub Issue

NA

## Related Jira Key

[CF-952](https://usdot-carma.atlassian.net/browse/CF-952)

## Motivation and Context

The bypass lane is needed for the DOT HQ demo.

## How Has This Been Tested?

Tested the Port Drayage demo on the vehicle. Once the vehicle arrived at the dropoff station, it was manually instructed to skip the port via Rviz. Worked with both the center line graph and the standard graph.

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

[CF-952]: https://usdot-carma.atlassian.net/browse/CF-952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by john-chrosniak** [comment]
center_line_graph

**Comment by john-chrosniak** [comment]
trailer_graph

**Review by willjohnsonk — CHANGES_REQUESTED** [review]
Suggest removal of old .geojson files including:
- chub.geojson
- f125_graph.geojson
- garage_graph_port_drayage_v0.geojson
- saxtonlab_graph.geojson

**Review by willjohnsonk — APPROVED** [review]
lgtm

**Pull request merged**
